# Generated by Django 6.0.3 on 2026-04-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='content',
        ),
        migrations.AddField(
            model_name='module',
            name='category',
            field=models.CharField(choices=[('easy_read', 'Easy Read'), ('course_material', 'Course Material')], default='course_material', help_text='Easy Read or Course Material', max_length=20),
        ),
        migrations.AddField(
            model_name='module',
            name='is_free',
            field=models.BooleanField(default=False, help_text='If true, this module is accessible without a subscription'),
        ),
        migrations.AddField(
            model_name='station',
            name='page_count',
            field=models.PositiveIntegerField(default=1, help_text='Total number of pages in the PDF. Set this after uploading.'),
        ),
        migrations.AddField(
            model_name='station',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Upload the PDF for this station. Will be served inline — not downloadable.', null=True, upload_to='stations/pdfs/'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='current_page',
            field=models.PositiveIntegerField(default=1, help_text='Last page the user was reading'),
        ),
        migrations.AlterField(
            model_name='module',
            name='long_text',
            field=models.TextField(help_text='Full description (rich text, shown on module detail page)'),
        ),
        migrations.AlterField(
            model_name='readingarticle',
            name='article_type',
            field=models.CharField(choices=[('easy_read', 'Easy Read'), ('course_material', 'Course Material')], default='course_material', max_length=20),
        ),
        migrations.AlterField(
            model_name='readingarticle',
            name='overview_text',
            field=models.TextField(blank=True, help_text='Extended description shown on the module detail page'),
        ),
        migrations.AlterField(
            model_name='readingarticle',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='articles/thumbnails/'),
        ),
        migrations.AlterField(
            model_name='station',
            name='is_free',
            field=models.BooleanField(default=False, help_text='Free preview station (first station should be free)'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='progress_percent',
            field=models.PositiveIntegerField(default=0, help_text='0-100, auto-calculated from page progress'),
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='videos/thumbnails/'),
        ),
    ]
