# Generated by Django 6.0.3 on 2026-06-26 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_station_content_module_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVideoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_time', models.FloatField(default=0.0, help_text='Last watched time in seconds')),
                ('progress_percent', models.PositiveIntegerField(default=0, help_text='0-100, auto-calculated from video length')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_progress', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='content.video')),
            ],
            options={
                'verbose_name': 'User Video Progress',
                'verbose_name_plural': 'User Video Progress',
                'unique_together': {('user', 'video')},
            },
        ),
    ]
