# Generated by Django 6.0.3 on 2026-06-26 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_uservideoprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(blank=True, help_text='Upload video file directly. Max 100MB.', null=True, upload_to='videos/files/'),
        ),
        migrations.AlterField(
            model_name='video',
            name='embed_url',
            field=models.URLField(blank=True, help_text='YouTube or Vimeo embed URL (e.g. https://www.youtube.com/embed/VIDEO_ID).', null=True),
        ),
    ]
