# Generated by Django 6.0.3 on 2026-06-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_video_video_file_alter_video_embed_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('exam_passed', models.CharField(blank=True, help_text="e.g. 'Passed Part 3'", max_length=255)),
                ('quote', models.TextField()),
                ('rating', models.PositiveIntegerField(default=5, help_text='1 to 5 stars')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/photos/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
