# Generated by Django 6.0.3 on 2026-04-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_coupon_paymenttransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='plan_category',
            field=models.CharField(choices=[('reading', 'Reading Modules'), ('video', 'Video Modules'), ('mock_exam', 'Mock Exam'), ('full', 'Full Access (Reading + Video + Mock Exam)')], default='full', help_text='What type of content this plan unlocks', max_length=20),
        ),
        migrations.AlterField(
            model_name='plan',
            name='duration_days',
            field=models.PositiveIntegerField(default=365, help_text='Number of days this plan is valid for'),
        ),
    ]
