# Generated by Django 6.0.3 on 2026-04-08 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_plan_plan_category_alter_plan_duration_days'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='bundles/thumbnails/')),
                ('short_description', models.CharField(help_text='Shown on the bundle card', max_length=300)),
                ('description', models.TextField(help_text='Full description shown in the detail modal')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='GBP', max_length=3)),
                ('duration_days', models.PositiveIntegerField(default=365, help_text='How many days this bundle is valid after purchase')),
                ('includes_reading', models.BooleanField(default=False, help_text='Unlocks Reading Library')),
                ('includes_video', models.BooleanField(default=False, help_text='Unlocks Video Library')),
                ('includes_mock_exam', models.BooleanField(default=False, help_text='Unlocks Mock Exam')),
                ('is_featured', models.BooleanField(default=False, help_text="Show 'Best Value' badge")),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order on the page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bundle',
                'verbose_name_plural': 'Bundles',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='country_code',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='gateway',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('pakistan', 'Pakistan Payment'), ('free', 'Free / Manual')], default='stripe', max_length=20),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='library_access',
            field=models.CharField(blank=True, help_text='The library this subscription row unlocks (reading/video/mock_exam)', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='subscriptions.plan'),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='subscriptions.plan'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='subscriptions.bundle'),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='bundle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='subscriptions.bundle'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.bundle')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='subscriptions.cart')),
            ],
            options={
                'verbose_name': 'Cart Item',
                'verbose_name_plural': 'Cart Items',
                'unique_together': {('cart', 'bundle')},
            },
        ),
    ]
