# Generated by Django 6.0.3 on 2026-06-29 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_bundle_paymenttransaction_country_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bundle',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
        migrations.AlterField(
            model_name='plan',
            name='currency',
            field=models.CharField(default='INR', max_length=3),
        ),
    ]
