# Generated by Django 6.0.3 on 2026-04-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_country_user_exam_batch_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpverification',
            name='purpose',
            field=models.CharField(choices=[('email_verify', 'Email Verification'), ('login', 'Login OTP'), ('password_reset', 'Password Reset'), ('register_verify', 'Registration Verification')], max_length=20),
        ),
    ]
